### ISSUE TITLE
More Definition Messages as in the garmin SDK

### ISSUE THREAD

**Issue by inonoob** [polyvertex/fitdecode#15]
Hey

I found the project fit4ruby [link](https://github.com/scrapper/fit4ruby). If you check the source code of GlobalFitMessages.rb [link](https://github.com/scrapper/fit4ruby/blob/master/lib/fit4ruby/GlobalFitMessages.rb)  and GlobalFitDictionaries.rb [link](https://github.com/scrapper/fit4ruby/blob/master/lib/fit4ruby/GlobalFitDictionaries.rb)  you got more definition messages as it contains in the official Garmin sdk. You might wanna check it out. 

Best regards

**Comment by renschler** [comment]
@inonoob nice find! any idea where they got them from? you said the garmin SDK but i downloaded the fit sdk from garmin and I dont see these values in their profile.xlsx file

**Comment by inonoob** [comment]
Hey, 
I thing they got them from try and error. For example, my Garmin watch creates in the Activity FIT file a special "definition message" and "data message" which is marked as unknown if I decode it with the SDK. But if I look closely, I can see my age, my height, my weight, my heart rate,my VO2max (MET)  but also other things which I can't decode. 
So yeah like I wrote on my repo, The Garmin SDK is far from complete

**Comment by polyvertex** [comment]
Thanks for this!

However this will probably remain as a `wontfix` since there is too much uncertainty in data reliability and because there is no way I can test the correctness of those types definitions.

I would rather keep *fitdecode*'s `profile.py` being generated exclusively by using the types definitions provided by the official FIT SDK for now.
